module.exports = {
  rollups: [
    {
      type: "doc",
      id: "overview",
      label: "Overview",
    },
    {
      type: "doc",
      id: "quickstart",
      label: "Quickstart",
    },
    {
      type: "category",
      label: "Core Concepts",
      collapsed: true,
      items: [
        "core-concepts/optimistic-rollups",
        "core-concepts/architecture",
        "core-concepts/mainnet-considerations",
        {
          type: "category",
          label: "Rollups HTTP APIs",
          collapsed: true,
          link: {
            type: "doc",
            id: "core-concepts/rollup-http-api/http-api",
          },
          items: [
            "core-concepts/rollup-http-api/http-api",
            {
              type: "category",
              label: "Backend APIs",
              link: {
                type: "doc",
                id: "core-concepts/rollup-http-api/backend/introduction",
              },
              collapsed: true,
              items: [
                "core-concepts/rollup-http-api/backend/introduction",
                "core-concepts/rollup-http-api/backend/notices",
                "core-concepts/rollup-http-api/backend/vouchers",
                "core-concepts/rollup-http-api/backend/reports",
              ],
            },
            {
              type: "category",
              label: "Frontend APIs",
              collapsed: true,
              items: [
                {
                  type: "category",
                  label: "Smart contracts API",
                  link: {
                    type: "doc",
                    id: "core-concepts/rollup-http-api/json-rpc/overview",
                  },
                  collapsed: true,
                  items: [
                    "core-concepts/rollup-http-api/json-rpc/overview",
                    "core-concepts/rollup-http-api/json-rpc/input-box",
                    "core-concepts/rollup-http-api/json-rpc/application",
                    "core-concepts/rollup-http-api/json-rpc/application-factory",

                    {
                      type: "category",
                      label: "Portals",
                      collapsed: true,
                      items: [
                        "core-concepts/rollup-http-api/json-rpc/portals/ERC20Portal",
                        "core-concepts/rollup-http-api/json-rpc/portals/ERC721Portal",
                        "core-concepts/rollup-http-api/json-rpc/portals/ERC1155SinglePortal",
                        "core-concepts/rollup-http-api/json-rpc/portals/ERC1155BatchPortal",
                        "core-concepts/rollup-http-api/json-rpc/portals/EtherPortal",
                      ],
                    },
                    {
                      type: "category",
                      label: "Relayer",
                      collapsed: true,
                      items: ["core-concepts/rollup-http-api/json-rpc/relays/relays"],
                    },
                  ],
                },
                {
                  type: "category",
                  label: "GraphQL API",
                  link: {
                    type: "doc",
                    id: "core-concepts/rollup-http-api/graphql/overview",
                  },
                  collapsed: true,
                  items: [
                    "core-concepts/rollup-http-api/graphql/overview",
                    {
                      type: "category",
                      label: "Queries",
                      collapsed: true,
                      items: [
                        {
                          type: "autogenerated",
                          dirName: "core-concepts/rollup-http-api/graphql/queries",
                        },
                      ],
                    },
                    {
                      type: "category",
                      label: "Objects",
                      collapsed: true,
                      items: [
                        {
                          type: "autogenerated",
                          dirName: "core-concepts/rollup-http-api/graphql/objects",
                        },
                      ],
                    },
                    {
                      type: "category",
                      label: "Filters",
                      collapsed: true,
                      items: [
                        {
                          type: "autogenerated",
                          dirName: "core-concepts/rollup-http-api/graphql/inputs",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Development",
      collapsed: true,
      items: [
        "development/installation",
        "development/creating-application",
        "development/building-the-application",
        "development/running-the-application",
        "development/node-configuration",
        "development/send-requests",
        "development/retrieve-outputs",

        {
          type: "category",
          label: "Assets Handling",
          collapsed: true,
          items: [
            "development/assets-handling/overview",
            {
              type: "doc",
              id: "development/assets-handling/javascript",
              label: "JavaScript",
            },
            {
              type: "doc",
              id: "development/assets-handling/python",
              label: "Python",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      collapsed: true,
      items: ["tutorials/calculator", "tutorials/machine-learning"],
    },

    {
      type: "category",
      label: "References",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Releases",
          items:[
            
            {
              type: "link",
              label: "Rollups Node",
              href: "https://github.com/cartesi/rollups-node/releases",
            },
            {
              type: "link",
              label: "Rollups Contracts",
              href: "https://github.com/cartesi/rollups-contracts/releases",
            },

          ],
        },
        {
          type: "category",
          label: "Changelog",
          items:[
            
            {
              type: "link",
              label: "Rollups Node",
              href: "https://github.com/cartesi/rollups-node/blob/main/CHANGELOG.md",
            },
            {
              type: "link",
              label: "Rollups Contracts",
              href: "https://github.com/cartesi/rollups-contracts/blob/main/CHANGELOG.md",
            },

          ],
        },
      ],
    },
    // {
    //   type: "category",
    //   label: "Future Developments",
    //   link: {
    //     type: "doc",
    //     id: "challenges/overview",
    //   },
    //   collapsed: true,
    //   items: ["challenges/overview"],
    // },
  ],
};
