module.exports = {
  rollups: [
    {
      type: "doc",
      id: "overview",
      label: "Overview",
    },
    {
      type: "doc",
      id: "quickstart",
      label: "Quickstart",
    },
    {
      type: "category",
      label: "Core Concepts",
      collapsed: true,
      items: [
      "core-concepts/why-cartesi",
      "core-concepts/optimistic-rollups",
      "core-concepts/architecture",   
        {
          type: "category",
          label: "Rollups HTTP APIs",
          collapsed: true,
          link: {
            type: "doc",
            id: "api/http-api",
          },
          items: [
            "api/http-api",
            {
              type: "category",
              label: "Frontend APIs",
              collapsed: true,
              items: [
                {
                  type: "category",
                  label: "Smart contracts API",
                  link: {
                    type: "doc",
                    id: "api/json-rpc/basics",
                  },
                  collapsed: true,
                  items: [
                    "api/json-rpc/basics",
                    "api/json-rpc/sol-input",
                    "api/json-rpc/sol-output",
                    {
                      type: "category",
                      label: "Portals",
                      collapsed: true,
                      items: [
                        "api/json-rpc/portals/ERC20Portal",
                        "api/json-rpc/portals/ERC721Portal",
                        "api/json-rpc/portals/ERC1155BatchPortal",
                        "api/json-rpc/portals/ERC1155SinglePortal",
                        "api/json-rpc/portals/EtherPortal",
                      ],
                    },
                    {
                      type: "category",
                      label: "Relayer",
                      collapsed: true,
                      items: ["api/json-rpc/relays/DAppAddressRelay"],
                    },
                  ],
                },
                {
                  type: "category",
                  label: "GraphQL API",
                  link: {
                    type: "doc",
                    id: "api/graphql/overview",
                  },
                  collapsed: true,
                  items: [
                    "api/graphql/overview",
                    {
                      type: "category",
                      label: "Queries",
                      collapsed: true,
                      items: [
                        {
                          type: "autogenerated",
                          dirName: "api/graphql/queries",
                        },
                      ],
                    },
                    {
                      type: "category",
                      label: "Objects",
                      collapsed: true,
                      items: [
                        {
                          type: "autogenerated",
                          dirName: "api/graphql/objects",
                        },
                      ],
                    },
                    {
                      type: "category",
                      label: "Filters",
                      collapsed: true,
                      items: [
                        {
                          type: "autogenerated",
                          dirName: "api/graphql/inputs",
                        },
                      ],
                    },
                  ],
                },
                "api/inspect/inspect",
              ],
            },
            {
              type: "category",
              label: "Backend APIs",
              link: {
                type: "doc",
                id: "api/rollup/cartesi-rollup-http-api",
              },
              collapsed: true,
              items: [
                "api/rollup/cartesi-rollup-http-api",
                "api/rollup/add-notice",
                "api/rollup/add-report",
                "api/rollup/add-voucher",
                "api/rollup/finish",
                "api/rollup/register-exception",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Development",
      collapsed: true,
      items: [
        "development/installation",
        "development/creating-application",
        "development/building-the-application",
        "development/running-the-application",
        "development/node-configuration",
        "development/send-requests",
        "development/retrieve-outputs",
        "development/assets-handling",
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      collapsed: true,
      items: ["tutorials/calculator", "tutorials/machine-learning"],
    },

    // {
    //   type: "category",
    //   label: "References",
    //   collapsed: true,
    //   items: [
    //     {
    //       type: "link",
    //       label: "Code samples",
    //       href: "https://github.com/cartesi/rollups-examples",
    //     },
    //     {
    //       type: "link",
    //       label: "Releases",
    //       href: "https://github.com/cartesi/rollups/releases",
    //     },
    //     {
    //       type: "category",
    //       label: "Migration guides",
    //       collapsed: true,
    //       items: ["migration-guides/from-09-to-10"],
    //     },
    //   ],
    // },
    // {
    //   type: "category",
    //   label: "Future Developments",
    //   link: {
    //     type: "doc",
    //     id: "challenges/overview",
    //   },
    //   collapsed: true,
    //   items: ["challenges/overview"],
    // },
  ],
};
