name: Build

on:
  pull_request:
    branches:
      - main
      - "release/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: yarn install

      - name: Build Docusaurus site
        run: yarn build
